In [ ]:
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent if '__file__' in globals() else Path.cwd().parent
sys.path.insert(0, str(project_root))

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = str(project_root / 'evaluation/loc_output/locagent/merged_loc_outputs_mrr.jsonl')
dataset_path = str(project_root / 'data/Loc-Bench_V1_dataset.jsonl')

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

ModuleNotFoundError: No module named 'evaluation'

In [5]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/locagent_20260102_072821/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

   file             module        function
  Acc@1 Acc@3 Acc@5  Acc@5 Acc@10    Acc@5 Acc@10
0   0.0   0.0   0.0    0.0    0.0      0.0    0.0

In [6]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/bm25_locbench/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.3696  0.4607  0.5339  0.3589  0.4143   0.2393  0.2786

In [7]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/bm25_ast/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                 module        function
    Acc@1   Acc@3   Acc@5  Acc@5 Acc@10    Acc@5 Acc@10
0  0.3714  0.4607  0.5339    0.0    0.0      0.0    0.0

In [8]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/bm25_graph/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module        function
    Acc@1   Acc@3   Acc@5   Acc@5 Acc@10    Acc@5  Acc@10
0  0.3714  0.4607  0.5339  0.3679  0.425   0.2429  0.2821

In [11]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/locagent_qwen25_7b_fixed_full/merged_loc_outputs_mrr.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.4321  0.4964  0.5071  0.1696  0.1839   0.1107  0.1232

In [10]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_locator_fixed/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.1732  0.2929  0.3625  0.2054  0.2875   0.1107  0.1536

In [11]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_graph/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                 module        function
    Acc@1   Acc@3   Acc@5  Acc@5 Acc@10    Acc@5 Acc@10
0  0.1732  0.2929  0.3625    0.0    0.0      0.0    0.0

In [12]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_locator_sliding/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.1821  0.3071  0.3821  0.2089  0.3018   0.0964  0.1429

In [13]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_fixed_spans_ast/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.1732  0.2929  0.3625  0.2054  0.2875   0.1107  0.1536

In [14]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_fixed_spans_graph/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.1732  0.2929  0.3625  0.2482  0.3357   0.1393  0.1804

In [15]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/bm25_results/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module        function
    Acc@1   Acc@3   Acc@5   Acc@5 Acc@10    Acc@5  Acc@10
0  0.3714  0.4607  0.5339  0.3679  0.425   0.2429  0.2821

In [16]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/bm25_graph/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module        function
    Acc@1   Acc@3   Acc@5   Acc@5 Acc@10    Acc@5  Acc@10
0  0.3714  0.4607  0.5339  0.3679  0.425   0.2429  0.2821

In [12]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_sliding_spans_graph/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

JSONDecodeError: Expecting ',' delimiter: line 1 column 2902 (char 2901)

In [ ]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_sliding_spans_ast/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.1821  0.3071  0.3821  0.2089  0.3018   0.0964  0.1429

In [ ]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_fixed_BS50_graph/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.1429  0.2411  0.2964  0.1929  0.2464   0.0875  0.1125

In [ ]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_fixed_unixcoderBS50_graph/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.0946  0.1607  0.2196  0.0982  0.1321   0.0107  0.0339

In [4]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_unixcoder_epic_ast/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module        function
    Acc@1   Acc@3   Acc@5   Acc@5 Acc@10    Acc@5  Acc@10
0  0.1696  0.2911  0.3625  0.1554    0.2   0.0571  0.0911

In [ ]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/locagent_qwen25_32b_new/merged_loc_outputs_mrr.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

/root/miniconda3/envs/locagent/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.6536  0.6839  0.7125  0.4446  0.4732   0.3196  0.3429

In [14]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_sliding_w64s4/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.1893  0.2911  0.3625  0.1964  0.2518      0.1  0.1304

In [15]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_sliding_unixcoderw64s4/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5 Acc@10
0  0.1107  0.1661  0.2286  0.1054  0.1482   0.0304   0.05

In [2]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_coderank_epic/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.3411  0.4911  0.6089  0.3589  0.4286   0.1964  0.2571

In [1]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_coderank_function_level/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

/root/miniconda3/envs/locagent/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

    file                  module         function
   Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.225  0.4339  0.5411  0.3482  0.4214   0.2268  0.2839

In [2]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/dense_coderank_function_level_new/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                 module         function
    Acc@1   Acc@3   Acc@5  Acc@5  Acc@10    Acc@5  Acc@10
0  0.2196  0.3964  0.5214  0.325  0.3911   0.2036  0.2643

In [1]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/coderank_langchain_recursive/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

/root/miniconda3/envs/locagent/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.4446  0.6036  0.6714  0.1286  0.1446   0.0375  0.0464

In [3]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/coderank_langchain_token/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.4107  0.5607  0.6429  0.2161  0.2393   0.0696  0.0804

In [4]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/coderank_langchain_fixed/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.4411  0.5893  0.6714  0.1714  0.1839     0.05  0.0589

In [7]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/llamaindex_token_CodeRankEmbed/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                 module         function
    Acc@1   Acc@3   Acc@5  Acc@5  Acc@10    Acc@5  Acc@10
0  0.3911  0.5429  0.6357  0.225  0.2554   0.0804  0.0857

In [6]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/llamaindex_sentence_CodeRankEmbed/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.3536  0.5161  0.6232  0.2304  0.2786   0.0768  0.1036

In [5]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/llamaindex_code_CodeRankEmbed/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

   file                  module        function
  Acc@1   Acc@3   Acc@5   Acc@5 Acc@10    Acc@5  Acc@10
0  0.45  0.5821  0.6589  0.1607  0.175   0.0464  0.0554

In [12]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/new_langchain_recursive_coderank/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                 module         function
    Acc@1   Acc@3  Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.4375  0.5982  0.675  0.4036  0.4911   0.2411  0.3018

In [9]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/new_langchain_fixed_coderank/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.4518  0.5946  0.6661  0.3982  0.4929   0.2286  0.2911

In [10]:
import sys
sys.path.append('/workspace/LocAgent')

from evaluation.eval_metric import evaluate_results

level2key_dict = {
    'file': 'found_files',
    'module': 'found_modules',
    'function': 'found_entities',
}

# 评测 LocAgent 结果（替换为你的实际输出目录）
loc_file = '/workspace/LocAgent/outputs/new_langchain_token_coderank/loc_outputs.jsonl'
dataset_path = '/workspace/LocAgent/data/Loc-Bench_V1_dataset.jsonl'

result = evaluate_results(
    loc_file,
    level2key_dict,
    metrics=['acc'],  # 可选: ['acc', 'recall', 'ndcg', 'precision', 'map']
    dataset_path=dataset_path
)
result

     file                  module         function
    Acc@1   Acc@3   Acc@5   Acc@5  Acc@10    Acc@5  Acc@10
0  0.4054  0.5589  0.6464  0.3821  0.4571   0.2089  0.2929